---
name: "Tests and checks"
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Nix checks
        run: nix flake check -L
  build:
    name: ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#luarocks-tag-release-action
          - .#devShells.x86_64-linux.default
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v16
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --accept-flake-config "${{matrix.attribute}}" -L
